name: tutors
description: Addicted To Excellence

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0-dev+2 #dev
#version: 1.0.0+1 #release

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.3



  animated_text_kit: ^4.2.1
  curved_navigation_bar: ^1.0.1
  flutter_svg: ^0.22.0
  get: ^4.3.8
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  url_launcher: ^6.0.12
  flutter_downloader: ^1.7.0
  path_provider: ^2.0.5
  permission_handler: ^8.1.6
  file_picker: ^4.1.3
#  flutter_local_notifications: ^6.0.0


  # Firebase
  firebase_core: ^1.7.0
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.2
  google_sign_in: ^5.1.1
  firebase_storage: ^10.0.4
  firebase_messaging: ^10.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: Seti
      fonts:
        - asset: fonts/seti.ttf